services:

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timesheet
    ports:
      - "3306:3306"

  timesheet:
    image: timesheet-project_timesheet:latest
    container_name: timesheet
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/timesheet?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
